#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-frozenlist
Version  : 1.2.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/5c/ee/7c6287928ba776567603248e160387cf4143641ecf734e393ad9b2c82475/frozenlist-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/5c/ee/7c6287928ba776567603248e160387cf4143641ecf734e393ad9b2c82475/frozenlist-1.2.0.tar.gz
Summary  : A list-like structure which implements collections.abc.MutableSequence
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-frozenlist-license = %{version}-%{release}
Requires: pypi-frozenlist-python = %{version}-%{release}
Requires: pypi-frozenlist-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: frozenlist
Provides: frozenlist-python
Provides: frozenlist-python3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
==========
frozenlist
==========
.. image:: https://github.com/aio-libs/frozenlist/workflows/CI/badge.svg
:target: https://github.com/aio-libs/frozenlist/actions
:alt: GitHub status for master branch

%package license
Summary: license components for the pypi-frozenlist package.
Group: Default

%description license
license components for the pypi-frozenlist package.


%package python
Summary: python components for the pypi-frozenlist package.
Group: Default
Requires: pypi-frozenlist-python3 = %{version}-%{release}

%description python
python components for the pypi-frozenlist package.


%package python3
Summary: python3 components for the pypi-frozenlist package.
Group: Default
Requires: python3-core
Provides: pypi(frozenlist)

%description python3
python3 components for the pypi-frozenlist package.


%prep
%setup -q -n frozenlist-1.2.0
cd %{_builddir}/frozenlist-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641436979
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-frozenlist
cp %{_builddir}/frozenlist-1.2.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-frozenlist/2da4a3eea24ffca0a87562a6bff54344c074a108
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-frozenlist/2da4a3eea24ffca0a87562a6bff54344c074a108

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
